config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  devise_for :users, controllers: {
    confirmations:      'users/confirmations',
    passwords:          'users/passwords',
    registrations:      'users/registrations',
    sessions:           'users/sessions',
    unlocks:            'users/unlocks'
  }

  resources :teams, only: [:new, :create, :destroy] do
    resources :memberships, only: [:index, :new, :create, :destroy]
  end
  post "/teams/switch/:id" => 'teams#switch', as: 'team_switch'

  resources :products, shallow: true do
    resources :projects, except: :index do
      resources :features, except: :index
    end
    resources :features, only: :index
  end

  post   '/product/:id' => 'active_products#create', as: 'active_product'
  get    '/product/:id' => 'active_products#show',   as: 'alt_product'
  delete '/product/all' => 'active_products#destroy'

  post   '/project/:id' => 'active_projects#create', as: 'active_project'
  get    '/project/:id' => 'active_projects#show',   as: 'alt_project'
  delete '/project/all' => 'active_projects#destroy'

  get '/complete' => 'completed_features#index'

end

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid" style="padding: 0 5em">
  	<% if current_user %>
    	<!-- Team -->
      <ul class="nav navbar-nav">
        <li>
          <%= link_to project_all_path, method: :delete do %>
            <span class="glyphicon glyphicon-home"></span>
          <% end %>
        </li>
        <li class="dropdown">
          <%= link_to '#', class: "dropdown-toggle", data: { toggle: 'dropdown' }, role: 'button',
              aria: { haspopup: "true", expanded: 'false' } do %>
            <%= current_user.team.nil? ? "Team" : current_user.team.name %>
        		<span class="caret"></span>
          <% end %>
          <ul class="dropdown-menu">
          	<% current_user.teams.each do |t| %>
          	<li>
          		<%= link_to team_switch_path(t), method: :post do %>
          			<%= t.name %>
          		<% end %>
          	</li>
          	<% end %>
          	<% if current_user.team %>
          	<li role="separator" class="divider"></li>
          	<% end %>
            <li>
            	<%= link_to new_team_path do %>
                <span class="glyphicon glyphicon-plus"></span>
                New Team
              <% end %>
            </li>
          </ul>
        </li>

        <% if current_user.team %>
          <li>
            <%= link_to team_memberships_path(current_user.team) do %>
              <span class="glyphicon glyphicon-user"></span>
              Members
            <% end %>
          </li>
        <% end # if current_user.team %>
      </ul>
    <% end # if current_user %>

  	<% if current_user %>
    <div class="pull-right">
    	<%= link_to 'Sign Out', destroy_user_session_path, method: :delete,
    	    class: "navbar-text navbar-right navbar-link" %>
    	<% end %>
    </div>
  </div>
</nav>

app/views/shared/_secondary_navigation_bar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" style="padding-top:50px;background-color:#fff;">
  <div class="container-fluid" style="padding: 0 5em">
    <h3 class='pull-left'>
      <%= link_to current_user.active_product.name, project_all_path, method: :delete %>
    </h3>

    <%= link_to product_all_path, method: :delete, class: "tooltipper pull-left", data:
        { toggle: "tooltip", placement: "bottom" }, title: "Other Products" do %>
        <h4 style="margin:0.5em" ><i class="fa fa-times"></i></h4>
    <% end %>

    <div class="pull-right">
      <%= link_to edit_product_path(current_user.active_product), class: "tooltipper pull-left", data:
          { toggle: "tooltip", placement: "bottom" }, title: "Edit Product" do %>
        <h3><small>
        	<span class="fa-stack" style="margin: 0 2em;">
        	  <i class="fa fa-circle fa-stack-2x"></i>
        	  <i class="fa fa-wrench fa-stack-1x fa-inverse"></i>
        	</span>
        </small></h3>
      <% end %>


      <%= link_to complete_path, class: "tooltipper pull-left", data:
          { toggle: "tooltip", placement: "bottom" }, title: "Completed Features" do %>
        <h3><small>
          <span class="fa-stack" style="margin: 0 2em;">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-check fa-stack-1x fa-inverse"></i>
          </span>
        </small></h3>
      <% end %>


      <%# link_to product_all_path, method: :delete, class: "tooltipper pull-left", data:
          { toggle: "tooltip", placement: "bottom" }, title: "Other Products" do %>

      <%= link_to product_features_path(current_user.active_product), class: "tooltipper pull-left", data:
          { toggle: "tooltip", placement: "bottom" }, title: "All Features" do %>
        <h3><small>
        	<span class="fa-stack" style="margin: 0 2em;">
        	  <i class="fa fa-circle fa-stack-2x" class="tooltipper"></i>
        	  <i class="fa fa-list-ul fa-stack-1x fa-inverse"></i>
        	</span>
        </small></h3>
      <% end %>
    </div>

  </div>
</nav>