config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  devise_for :users, controllers: {
    confirmations:      'users/confirmations',
    passwords:          'users/passwords',
    registrations:      'users/registrations',
    sessions:           'users/sessions',
    unlocks:            'users/unlocks'
  }

  resources :teams, only: [:new, :create, :destroy] do
    resources :memberships, only: [:index, :new, :create, :destroy]
  end
  post "/teams/switch/:id" => 'teams#switch', as: 'team_switch'

  resources :products, shallow: true do
    resources :projects, except: :index do
      resources :features, except: :index
    end
    resources :features, only: :index
  end

  post   '/product/:id' => 'active_products#create', as: 'active_product'
  get    '/product/:id' => 'active_products#show',   as: 'alt_product'
  delete '/product/all' => 'active_products#destroy'

  post   '/project/:id' => 'active_projects#create', as: 'active_project'
  get    '/project/:id' => 'active_projects#show',   as: 'alt_project'
  delete '/project/all' => 'active_projects#destroy'

  get '/complete' => 'completed_features#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  # belongs_to :team
  # has_many   :products
  # validates_presence_of :name, :team_id

  # before_destroy :set_active_projects_to_nil

  # def set_active_projects_to_nil
  # 	# loop through the memberships that have this project ID as 'active_project' and
  # 	# set value to nil.
  # 	TeamMembership.where(active_project_id: self.id).map { |m| m.update(active_project_id: nil) }
  # end

  # def features
  # 	self.products.map(&:features).flatten
  # end

  belongs_to :product
  has_many   :features, -> { order(position: :asc) }, dependent: :destroy

  validates_presence_of :name, :product_id

  before_destroy :set_active_products_to_nil

  after_create :add_mvp_and_demo

  def self.sorted
    all.sort_by{ |p| p.name.downcase }
  end

  def completed_features
    self.features.where(completed: true)
  end

  def active_features
    self.features.where(completed: false)
  end

  private

    def set_active_products_to_nil
      # loop through the memberships that have this product ID as 'active_product' and
      # set value to nil.
      TeamMembership.where(active_product_id: self.id).map { |m| m.update(active_product_id: nil) }
    end

    def add_mvp_and_demo
      # # Create a feature?
      self.features.build(name: "MVP").save
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /project
  # GET /project.json
  def index
    @project = Project.all
  end

  # GET /project/1
  # GET /project/1.json
  def show
    @completed_features = @project.completed_features
    @active_features    = @project.active_features
  end

  # GET /project/new
  def new
    @product = Product.find params[:product_id]
    @project = @product.projects.build
  end

  # GET /project/1/edit
  def edit
  end

  # POST /project
  # POST /project.json
  def create
    @product = Product.find params[:product_id]
    @project = @product.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project/1
  # PATCH/PUT /project/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project/1
  # DELETE /project/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to products_url(@project.product), notice: 'project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_features_loop.html.erb
<% scheduled_style = feature.scheduled ? "background-color:rgb(246, 250, 252)" : "" %>

<div style="padding:1.5em 1em;border-top:1px solid #ddd;<%= scheduled_style %>">
	<div class="row">

		<div class="col-xs-1">
			<%= simple_form_for feature, remote: true do |f| %>
				<%= f.hidden_field :completed, value: !feature.completed %>
				<%= button_tag type: 'submit', class: 'btn', style: "background-color:transparent;padding:0" do %>
					<% icon_class = feature.completed ? "fa-square-o" : "fa-check-square-o" %>
					<i class="tooltipper fa fa-lg <%= icon_class %>" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" }, title="Mark as <%= feature.completed ? "incomplete" : "complete" %>"></i>
				<% end %>
			<% end %>
		</div>

		<div class="col-md-9 col-xs-11">
<!--				<div style="width:1.5em;float:left">
 					<% if feature.completed %>
						<i class="fa fa-check-square-o" aria-hidden="true"></i>
					<% else %>
						<i class="fa fa-square-o" aria-hidden="true"></i>
					<% end %>



				</div> -->

				<%= button_tag class: 'btn btn-block', style: "background-color:transparent;padding:0;text-align: left;",
				    data: { toggle: "collapse", target: "#more-info-#{feature.id}" } do %>
					<span style="font-size:1.25em">
						<%= feature.name %>
					</span>
				<% end %>
			<div id="more-info-<%= feature.id %>" class="collapse">
				<!-- <span style="font-size:1.25em"><div style="width:1.5em;float:left">&nbsp;</div></span> -->
				<div style="float:left">
					<hr>
					<p style="font-weight:500">
						Estimated Time:
						<%= feature.estimated_days ? pluralize(feature.estimated_days, "Day") : "--"  %>
					</p>
					<p style="font-weight:500">Description</p>
					<p><%= markdown feature.description %></p>
				</div>
			</div>
		</div>

<!-- 		<div class="col-md-1 col-xs-3 center">
			<%= button_tag class: 'btn', style: "background-color:transparent;padding:0",
			    data: { toggle: "collapse", target: "#more-info-#{feature.id}" } do %>
				<% icon_class = feature.scheduled ? "fa-calendar-minus-o" : "fa-calendar-check-o" %>
				<i class="tooltipper fa fa-lg fa-info" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" }, title="More Info"></i>
			<% end %>
		</div> -->

		<div class="col-md-1 col-xs-3 center">
			<%= simple_form_for feature, remote: true do |f| %>
				<%= f.hidden_field :scheduled, value: !feature.scheduled %>
				<%= button_tag type: 'submit', class: 'btn', style: "background-color:transparent;padding:0" do %>
					<% icon_class_s = feature.scheduled ? "fa-calendar-minus-o" : "fa-calendar-check-o" %>
					<i class="tooltipper fa fa-lg <%= icon_class_s %>" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" }, title="<%= feature.scheduled ? 'Remove from' : 'Add to' %> schedule"></i>
				<% end %>
			<% end %>
		</div>

<!-- 		<div class="col-md-1 col-xs-3 center">
			<%= simple_form_for feature, remote: true do |f| %>
				<%= f.hidden_field :completed, value: !feature.completed %>
				<%= button_tag type: 'submit', class: 'btn', style: "background-color:transparent;padding:0" do %>
					<% icon_class = feature.completed ? "fa-minus" : "fa-check" %>
					<i class="tooltipper fa fa-lg <%= icon_class %>" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" }, title="Mark as <%= feature.completed ? "incomplete" : "complete" %>"></i>
				<% end %>
			<% end %>
		</div> -->

		<div class="col-md-1 col-xs-3 center">
			<!-- <i class="tooltipper fa fa-lg fa-trash-o" aria-hidden="true"></i data-toggle="tooltip" data-placement="bottom" }, title="All projects"> -->
			<%= link_to edit_feature_path(feature), class: 'btn', remote: true,
			    style: "background-color:transparent;padding:0;color:black" do %>
				<i class="tooltipper fa fa-lg fa-wrench" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" }, title="Edit Feature"></i>
			<% end %>
		</div>

	</div>
</div>

app/views/projects/_form.html.erb
<% url_path = @project.new_record? ? product_projects_path(@product) : project_path(@project) %>
<%= simple_form_for @project, url: url_path do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :name %>
  	<%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="container-fluid">
	<div class="col-md-offset-2 col-md-8">

		<%= link_to 'Back', product_path(@project.product), class: "pull-right" %>
		<h1>Editing project</h1>

		<%= render 'form' %>

		<hr>
		<%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure? Deleting this project will destroy all the associated data.' } %>

	</div>
</div>

app/views/projects/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New project', new_project_path %>
 -->

app/views/projects/new.html.erb
<div class="container-fluid">
	<div class="col-md-offset-2 col-md-8">

		<h1>New project</h1>

		<%= render 'form' %>

		<hr>

		<%= link_to 'Back', product_path(@product) %>

	</div>
</div>

app/views/projects/show.html.erb
<div class="container-fluid">
	<div class="col-md-offset-2 col-md-8">

		<div class="row">
			<div class="col-md-6">
				<h2 class="pull-left">
					<small>Project</small><br>
					<%= @project.name %>
				</h2>
			</div>

			<div class="col-md-6">

				<div style="padding: 1em 1em 0">
	        <%= link_to project_all_path, class: "tooltipper pull-right", method: :delete, data:
					    { toggle: "tooltip", placement: "bottom" }, title: "All projects",
					    style: "margin-left: 3em" do %>
	        	<h2>
	        		<small>
	        		<span class="fa-stack">
	        		  <i class="fa fa-circle fa-stack-2x"></i>
	        		  <i class="fa fa-chevron-left fa-stack-1x fa-inverse"></i>
	        		</span>
	        		</small>
	        	</h2>
	        <% end %>

          <%= link_to edit_project_path, class: "tooltipper pull-right", data:
  				    { toggle: "tooltip", placement: "bottom" }, title: "Edit project",
  				    style: "margin-left: 3em" do %>
          	<h2>
          		<small>
          		<span class="fa-stack">
          		  <i class="fa fa-circle fa-stack-2x"></i>
          		  <i class="fa fa-wrench fa-stack-1x fa-inverse"></i>
          		</span>
          		</small>
          	</h2>
          <% end %>
	      </div>
			</div>
		</div>

		<hr>

		<div class="row" style="padding-bottom:1em">
			<div class="col-md-12">
				<h3>Features:</h3>
			</div>
			<div class="col-md-4 col-xs-6">
				<%= link_to '#new-feature', data: { toggle: "collapse" } do %>
					<h3 class="pull-left" style="margin:-3px 7px 0">
						<i class="fa fa-plus-circle" aria-hidden="true"></i>
					</h3>
					New Feature
				<% end %>
			</div>
			<div class="col-md-4 col-xs-6">
				<%= link_to '#completed-features', data: { toggle: "collapse" } do %>
					<h3 class="pull-left" style="margin:-3px 7px 0">
						<i class="fa fa-check-circle" aria-hidden="true"></i>
					</h3>
					Show Completed (<%= @completed_features.count %>)
				<% end %>
			</div>
		</div>

		<div id="new-feature" class="collapse">
			<%= render 'features/form', feature: @project.features.build %>
		</div>

		<div id="completed-features" class="collapse">
			<% @completed_features.each do |f| %>
				<%= content_tag :div, id: "feature-#{f.id}" do %>
					<%= render 'features_loop', feature: f %>
				<% end %>
			<% end %>
		</div>

		<% @active_features.each do |f| %>
			<%= content_tag :div, id: "feature-#{f.id}" do %>
				<%= render 'features_loop', feature: f %>
			<% end %>
		<% end %>


	</div>
</div>