config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  devise_for :users, controllers: {
    confirmations:      'users/confirmations',
    passwords:          'users/passwords',
    registrations:      'users/registrations',
    sessions:           'users/sessions',
    unlocks:            'users/unlocks'
  }

  resources :teams, only: [:new, :create, :destroy] do
    resources :memberships, only: [:index, :new, :create, :destroy]
  end
  post "/teams/switch/:id" => 'teams#switch', as: 'team_switch'

  resources :products, shallow: true do
    resources :projects, except: :index do
      resources :features, except: :index
    end
    resources :features, only: :index
  end

  post   '/product/:id' => 'active_products#create', as: 'active_product'
  get    '/product/:id' => 'active_products#show',   as: 'alt_product'
  delete '/product/all' => 'active_products#destroy'

  post   '/project/:id' => 'active_projects#create', as: 'active_project'
  get    '/project/:id' => 'active_projects#show',   as: 'alt_project'
  delete '/project/all' => 'active_projects#destroy'

  get '/complete' => 'completed_features#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  # belongs_to :project
  # has_many   :features, -> { order(position: :asc) }, dependent: :destroy

  # validates_presence_of :name, :project_id

  # before_destroy :set_active_products_to_nil

  # after_create :add_mvp_and_demo

  # def self.sorted
  # 	all.sort_by{ |p| p.name.downcase }
  # end

  # def completed_features
  #   self.features.where(completed: true)
  # end

  # def active_features
  #   self.features.where(completed: false)
  # end

  # private

	 #  def set_active_products_to_nil
	 #  	# loop through the memberships that have this product ID as 'active_product' and
	 #  	# set value to nil.
	 #  	TeamMembership.where(active_product_id: self.id).map { |m| m.update(active_product_id: nil) }
	 #  end

  #   def add_mvp_and_demo
  #     # # Create a feature?
  #     self.features.build(name: "MVP").save
  #   end


  belongs_to :team
  has_many   :projects
  validates_presence_of :name, :team_id

  before_destroy :set_active_projects_to_nil

  def set_active_projects_to_nil
    # loop through the memberships that have this project ID as 'active_project' and
    # set value to nil.
    TeamMembership.where(active_project_id: self.id).map { |m| m.update(active_project_id: nil) }
  end

  def features
    self.projects.map(&:features).flatten
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if current_user.team.nil?
      redirect_to new_team_path
    elsif current_user.active_product.nil?
      @products = current_user.team.products
    else
      redirect_to product_path(current_user.active_product)
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    if current_user.team.nil?
      redirect_to new_team_path
    elsif current_user.active_product.nil?
      redirect_to products_path
    elsif current_user.active_project
      redirect_to project_path(current_user.active_project)
    else
      set_product
      @projects = @product.projects.sorted
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.team = current_user.team

    respond_to do |format|
      if @product.save
        membership = current_user.active_membership
        if membership.update active_product: @product
          format.html { redirect_to @product }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new, notice: "Something went wrong. #{error_message_for membership}" }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new, notice: "Something went wrong. #{error_message_for @product}" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_features_loop.html.erb
<% scheduled_style = feature.scheduled ? "background-color:rgb(246, 250, 252)" : "" %>

<div style="padding:1.5em 1em;border-top:1px solid #ddd;<%= scheduled_style %>">
	<div class="row">

		<div class="col-md-8">
			<span style="font-size:1.25em">
				<div style="width:1.5em;float:left">
				<% if feature.completed %>
				<i class="fa fa-check-square-o" aria-hidden="true"></i>
				<% else %>
				<i class="fa fa-square-o" aria-hidden="true"></i>
				<% end %>
				</div>
				<%= feature.name %>
			</span>
			<div id="more-info-<%= feature.id %>" class="collapse">
				<span style="font-size:1.25em"><div style="width:1.5em;float:left">&nbsp;</div></span>
				<div style="float:left">
					<hr>
					<h4 style="font-weight:200">Description</h4>
					<p><%= markdown feature.description %></p>
				</div>
			</div>
		</div>

		<div class="col-md-1 col-xs-3 center">
			<%= button_tag class: 'btn', style: "background-color:transparent;padding:0",
			    data: { toggle: "collapse", target: "#more-info-#{feature.id}" } do %>
				<% icon_class = feature.scheduled ? "fa-calendar-minus-o" : "fa-calendar-check-o" %>
				<i class="tooltipper fa fa-lg fa-info" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" }, title="More Info"></i>
			<% end %>
		</div>

		<div class="col-md-1 col-xs-3 center">
			<%= simple_form_for feature, remote: true do |f| %>
				<%= f.hidden_field :scheduled, value: !feature.scheduled %>
				<%= button_tag type: 'submit', class: 'btn', style: "background-color:transparent;padding:0" do %>
					<% icon_class_s = feature.scheduled ? "fa-calendar-minus-o" : "fa-calendar-check-o" %>
					<i class="tooltipper fa fa-lg <%= icon_class_s %>" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" }, title="<%= feature.scheduled ? 'Remove from' : 'Add to' %> schedule"></i>
				<% end %>
			<% end %>
		</div>

		<div class="col-md-1 col-xs-3 center">
			<%= simple_form_for feature, remote: true do |f| %>
				<%= f.hidden_field :completed, value: !feature.completed %>
				<%= button_tag type: 'submit', class: 'btn', style: "background-color:transparent;padding:0" do %>
					<% icon_class = feature.completed ? "fa-minus" : "fa-check" %>
					<i class="tooltipper fa fa-lg <%= icon_class %>" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" }, title="Mark as <%= feature.completed ? "incomplete" : "complete" %>"></i>
				<% end %>
			<% end %>
		</div>

		<div class="col-md-1 col-xs-3 center">
			<!-- <i class="tooltipper fa fa-lg fa-trash-o" aria-hidden="true"></i data-toggle="tooltip" data-placement="bottom" }, title="All Products"> -->
			<%= link_to edit_feature_path(feature), class: 'btn', remote: true,
			    style: "background-color:transparent;padding:0;color:black" do %>
				<i class="tooltipper fa fa-lg fa-wrench" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" }, title="Edit Feature"></i>
			<% end %>
		</div>

	</div>
</div>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :name %>
  	<%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container-fluid">
	<div class="col-md-offset-2 col-md-8">

		<%= link_to 'Back', @product, class: 'pull-right' %>
		<h1>Editing Product</h1>
		<hr>

		<%= render 'form' %>

		<hr>

		<%= link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' } %>

	</div>
</div>

app/views/products/index.html.erb
<div class="container-fluid">
  <div class="col-md-offset-2 col-md-8">

    <div class="row">
      <div class="col-md-12">

        <h4>
          Products
          <%= link_to new_product_path, class: "pull-right" do %>
            <i class="fa fa-plus-circle" aria-hidden="true"></i>
            New Product
          <% end %>
        </h4>
      </div>
    </div>
    <hr>

    <table>
      <!-- <thead>
        <tr>
          <th colspan="3"></th>
        </tr>
      </thead> -->

      <tbody>
        <% @products.each do |product| %>
          <tr>
            <%= link_to active_product_path(product), method: :post do %>
              <h3><%= product.name %></h3>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

  </div>
</div>

app/views/products/new.html.erb
<div class="container-fluid">
	<div class="col-md-offset-2 col-md-8">

		<h1>New Product</h1>

		<%= render 'form' %>

		<%= link_to 'Back', products_path %>

	</div>
</div>

app/views/products/show.html.erb
<div class="container-fluid">
	<div class="col-md-offset-2 col-md-8">

		<div class="row">
			<div class="col-md-10">
				<h2>
					<small><%= @product.name %></small><br>
					Projects
				</h2>
			</div>

			<div class="col-md-2 center" style="padding-top:2em">
					<%= link_to new_product_project_path(@product), class: "tooltipper", data:
					    { toggle: "tooltip", placement: "bottom" }, title: "New project" do %>
					  <h2><i class="fa fa-plus-circle" aria-hidden="true"></i></h2>
					<% end %>

				<!-- <div style="padding: 1em 1em 0">
					<%= link_to new_product_project_path(@product), class: "pull-right tooltipper", data:
					    { toggle: "tooltip", placement: "bottom" }, title: "New project" do %>
	        	<h3>
		        		<span class="fa-stack">
		        		  <i class="fa fa-circle fa-stack-2x"></i>
		        		  <i class="fa fa-plus fa-stack-1x fa-inverse"></i>
		        		</span>
		        </h3>
					<% end %>
				</div>-->
			</div>
		</div>

		<hr>

    <% @projects.each do |project| %>
      <div class="row">
      	<div class="col-xs-10">
        <%= link_to active_project_path(project), method: :post do %>
        	<h3 style='margin:0'><%= project.name %></h3>
        	<h4 style='margin:0'><small><%= pluralize(project.active_features.count, 'Incomplete Feature') %></small></h4>
        <% end %>
        </div>
        <div class="col-xs-2 center">
	        <%= link_to edit_project_path(project), class: "tooltipper", data:
					    { toggle: "tooltip", placement: "bottom" }, title: "Edit project" do %>
	        	<h3 style='margin:0'><small>
	        		<span class="fa-stack">
	        		  <i class="fa fa-circle fa-stack-2x"></i>
	        		  <i class="fa fa-wrench fa-stack-1x fa-inverse"></i>
	        		</span>
	        	</small></h3>
	        <% end %>
	      </div>
      </div>
      <hr>
    <% end %>




	</div>
</div>