config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  devise_for :users, controllers: {
    confirmations:      'users/confirmations',
    passwords:          'users/passwords',
    registrations:      'users/registrations',
    sessions:           'users/sessions',
    unlocks:            'users/unlocks'
  }

  resources :teams, only: [:new, :create, :destroy] do
    resources :memberships, only: [:index, :new, :create, :destroy]
  end
  post "/teams/switch/:id" => 'teams#switch', as: 'team_switch'

  resources :products, shallow: true do
    resources :projects, except: :index do
      resources :features, except: :index
    end
    resources :features, only: :index
  end

  post   '/product/:id' => 'active_products#create', as: 'active_product'
  get    '/product/:id' => 'active_products#show',   as: 'alt_product'
  delete '/product/all' => 'active_products#destroy'

  post   '/project/:id' => 'active_projects#create', as: 'active_project'
  get    '/project/:id' => 'active_projects#show',   as: 'alt_project'
  delete '/project/all' => 'active_projects#destroy'

  get '/complete' => 'completed_features#index'

end

app/models/feature.rb
class Feature < ActiveRecord::Base
  belongs_to :project
  acts_as_list scope: :project

  validates_presence_of :name, :project_id

  before_save :update_completed_date

  private

  	def update_completed_date
  		self.completed_date = Time.now if self.completed
  	end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :set_feature, only: [:show, :edit, :update, :destroy]

  # # GET /features
  # # GET /features.json
  def index
    # @product  = Product.find(params[:product_id])
    @product  = current_user.active_product
    @features = @product.projects.map(&:features).flatten.sort_by(&:created_at).reverse
  end

  # GET /features/1
  # GET /features/1.json
  def show
    respond_to :js
  end

  # GET /features/new
  def new
    @feature = Feature.new
    respond_to :js
  end

  # GET /features/1/edit
  def edit
    respond_to :js
  end

  # POST /features
  # POST /features.json
  def create
    @project = Project.find params[:project_id]
    @feature = @project.features.build(feature_params)

    respond_to do |format|
      if @feature.save
        format.html { redirect_to project_path(@feature.project), notice: 'Feature was successfully created.' }
        format.json { render :show, status: :created, location: @feature }
      else
        format.html { render :new }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /features/1
  # PATCH/PUT /features/1.json
  def update
    respond_to do |format|
      if @feature.update(feature_params)
        format.html { redirect_to project_path(@feature.project) }
        # format.json { render :show, status: :ok, location: @feature }
        format.js
      else
        format.html { redirect_to :back, notice: (error_message_for @feature) }
        # format.json { render json: @feature.errors, status: :unprocessable_entity }
        format.js   { @errors = error_message_for @feature }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature.destroy
    respond_to do |format|
      format.html { redirect_to project_path(@feature.project), notice: 'Feature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feature
      @feature = Feature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feature_params
      params.require(:feature).permit(:name, :description, :scheduled, :completed)
    end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/features/_form.html.erb
<div class="container-fluid" style="padding:2em">
	<div class="row">
		<%= link_to "#", class: 'pull-right' do %>
			<span class="glyphicon glyphicon-remove"></span>
			Cancel
		<% end %>
		<% url_path = feature.new_record? ? project_features_path(@project) : feature_path(feature) %>
		<%= simple_form_for(feature, url: url_path) do |f| %>
		  <%= f.error_notification %>

		  <div class="form-inputs">
		  	<%= f.input :name %>
		  	<%= f.input :estimated_days %>
		  	<%= f.input :description, input_html: { rows: 5 } %>
		  </div>

		  <div class="form-actions">
		    <%= f.button :submit %>
		  </div>
		<% end %>
		<%= link_to feature_path(feature), method: :delete, class: 'pull-right',
		    data: { confirm: 'Are you sure?' } do %>
			Delete
		<% end unless feature.new_record? %>
	</div>
</div>

app/views/features/edit.js.erb
$('#feature-<%= @feature.id %>').html('<%= j render "form", feature: @feature %>')

app/views/features/index.html.erb
<div class="container-fluid">
  <div class="col-md-8 col-md-offset-2">

    <h3>
      <small>Product:</small><br>
      <%= current_user.active_product.name %>
    </h3>

    <% @features.each do |feature| %>
      <hr>
      <div class="row">
        <div class="col-md-3 col-xs-4">
          <%# feature.completed_date.strftime("%A, %b/%m/%Y") %>
          <%= feature.created_at.strftime("%A") %> <br>
          <%= feature.created_at.strftime("%b/%m/%Y") %>
        </div>
        <div class="col-md-9 col-xs-8">
          <% if feature.completed %>
            <span class="glyphicon glyphicon-ok" style="margin-left:0em"></span>
          <% end %>
          <strong><%= feature.name %></strong><br>
          <small>
            Project:
            <%= link_to feature.project.name, active_project_path(feature.project) %>
          </small>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/features/new.html.erb
<h1>New Feature</h1>

<%= render 'form' %>

<%= link_to 'Back', features_path %>

app/views/features/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_feature_path(@feature) %> |
<%= link_to 'Back', features_path %>

app/views/features/update.js.erb
$('#feature-<%= @feature.id %>').html('<%= j render "projects/features_loop", feature: @feature %>');